INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('John Smith', '123 Main St, New York, NY 10001', 'john.smith@email.com', '555-0101', '1985-03-15');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Sarah Johnson', '456 Oak Ave, Los Angeles, CA 90210', 'sarah.johnson@email.com', '555-0102', '1990-07-22');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Michael Brown', '789 Pine Rd, Chicago, IL 60601', 'michael.brown@email.com', '555-0103', '1988-11-08');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Emily Davis', '321 Elm St, Houston, TX 77001', 'emily.davis@email.com', '555-0104', '1992-01-30');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('David Wilson', '654 Maple Dr, Phoenix, AZ 85001', 'david.wilson@email.com', '555-0105', '1987-09-12');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Jessica Miller', '987 Cedar Ln, Philadelphia, PA 19101', 'jessica.miller@email.com', '555-0106', '1991-05-18');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Christopher Garcia', '147 Birch St, San Antonio, TX 78201', 'chris.garcia@email.com', '555-0107', '1986-12-03');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Amanda Rodriguez', '258 Spruce Ave, San Diego, CA 92101', 'amanda.rodriguez@email.com', '555-0108', '1993-04-25');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Matthew Martinez', '369 Willow Rd, Dallas, TX 75201', 'matthew.martinez@email.com', '555-0109', '1989-08-14');
INSERT INTO customer (displayname, address, email, phone, birthday) VALUES ('Ashley Anderson', '741 Poplar St, San Jose, CA 95101', 'ashley.anderson@email.com', '555-0110', '1994-02-07');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Wireless Bluetooth Headphones', 79.99, 'Premium quality wireless headphones with noise cancellation and 30-hour battery life', '2024-01-15');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Gaming Mechanical Keyboard', 149.99, 'RGB backlit mechanical keyboard with tactile switches, perfect for gaming and typing', '2024-02-20');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Smartphone Case', 24.99, 'Durable protective case with shock absorption and wireless charging compatibility', '2024-03-10');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('4K USB Webcam', 89.99, 'High-definition webcam with auto-focus and built-in microphone for video calls', '2024-01-25');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Portable Power Bank', 39.99, '20000mAh portable charger with fast charging support for multiple devices', '2024-02-14');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Ergonomic Office Chair', 299.99, 'Adjustable office chair with lumbar support and breathable mesh back', '2024-01-08');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('LED Desk Lamp', 45.99, 'Adjustable LED desk lamp with multiple brightness levels and USB charging port', '2024-03-05');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Wireless Mouse', 34.99, 'Ergonomic wireless mouse with precision tracking and long battery life', '2024-02-28');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('Bluetooth Speaker', 64.99, 'Portable waterproof speaker with 360-degree sound and 12-hour battery', '2024-01-18');
INSERT INTO product (name, price, description, manufactureDate) VALUES ('USB-C Hub', 54.99, '7-in-1 USB-C hub with HDMI, USB ports, and SD card reader for laptops', '2024-03-12');
INSERT INTO CustomerTier (id, name) VALUES (1, 'Bronze');
INSERT INTO CustomerTier (id, name) VALUES (2, 'Silver');
INSERT INTO CustomerTier (id, name) VALUES (3, 'Gold');
INSERT INTO CustomerTier (id, name) VALUES (4, 'Platinum');
-- Insert sample ProductReview data
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (1, 1, 5, 'Excellent sound quality and battery life. Highly recommended!', '2024-03-01');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (1, 2, 4, 'Good headphones, comfortable to wear for long periods.', '2024-03-02');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (2, 3, 5, 'Amazing keyboard for gaming. The RGB lighting is fantastic!', '2024-03-03');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (2, 4, 4, 'Great tactile feedback, but a bit loud for office use.', '2024-03-04');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (3, 5, 3, 'Decent protection but could be more durable.', '2024-03-05');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (4, 6, 5, 'Crystal clear video quality, perfect for video conferences.', '2024-03-06');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (5, 7, 4, 'Fast charging and holds charge well. Good value for money.', '2024-03-07');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (6, 8, 5, 'Very comfortable chair, great for long work sessions.', '2024-03-08');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (7, 9, 4, 'Good lighting and USB port is convenient.', '2024-03-09');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (8, 10, 3, 'Works fine but the battery could last longer.', '2024-03-10');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (9, 1, 5, 'Great speaker with excellent sound quality and truly waterproof.', '2024-03-11');
INSERT INTO ProductReview (product_id, customer_id, rating, comment, reviewDate) VALUES (10, 2, 4, 'Very useful hub with all the ports I need.', '2024-03-12');